# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            NESCent
tagline:          'National Evolutionary Synthesis Center'
description:      'Information on digital assets of NESCent and plans for their handoff and archival.'
url:              http://nescent.org
baseurl:          /

author:
  name:           'Karen Cranston'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nescent/nescent.github.io
